### ISSUE TITLE
Add citation file in guidelines

### ISSUE THREAD

**Issue by AurelienBesnier** [openalea/openalea.rtfd.io#35]
# Rational
How do we cite softwares / papers or even datasets in a GitHub repository ?

# Solution
The [Citation File Format (CFF)](https://citation-file-format.github.io/) provide support for that and is even integrated in GitHub.

See [this link](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) for more information

For example, Phenomenal's citation file would look like this:
```yaml
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
- family-names: "Artzet"
  given-names: "Simon"
- family-names: "Chen"
  given-names: "Tsu-Wei"
  orcid: "https://orcid.org/0000-0001-6698-563X"
- family-names: "Chopard"
  given-names: "Jérôme"
- family-names: "Brichet"
  given-names: "Nicolas"
- family-names: "Mielewczik"
  given-names: "Michael"
  orcid: "https://orcid.org/0000-0002-3796-4183"
- family-names: "Cohen-Boulakia"
  given-names: "Sarah"
  orcid: "https://orcid.org/0000-0002-7439-1441"
- family-names: "Cabrera-Bosquet"
  given-names: "Llorenç"
  orcid: "https://orcid.org/0000-0002-2147-2846"
- family-names: "Tardieu"
  given-names: "François"
  orcid: "https://orcid.org/0000-0002-7287-0094"
- family-names: "Fournier"
  given-names: "Christian"
  orcid: "https://orcid.org/0000-0001-7098-8278"
- family-names: "Pradal"
  given-names: "Christophe"
  orcid: "https://orcid.org/0000-0002-2555-761X"
title: "Phenomenal: An automatic open source library for 3D shoot architecture reconstruction and analysis for image-based plant phenotyping"
version: 1.9.4
date-released: 2019-10-21
url: "https://github.com/openalea/phenomenal"

preferred-citation:
    type: article
    authors:
    - family-names: "Artzet"
      given-names: "Simon"
    - family-names: "Chen"
      given-names: "Tsu-Wei"
      orcid: "https://orcid.org/0000-0001-6698-563X"
    - family-names: "Chopard"
      given-names: "Jérôme"
    - family-names: "Brichet"
      given-names: "Nicolas"
    - family-names: "Mielewczik"
      given-names: "Michael"
      orcid: "https://orcid.org/0000-0002-3796-4183"
    - family-names: "Cohen-Boulakia"
      given-names: "Sarah"
      orcid: "https://orcid.org/0000-0002-7439-1441"
    - family-names: "Cabrera-Bosquet"
      given-names: "Llorenç"
      orcid: "https://orcid.org/0000-0002-2147-2846"
    - family-names: "Tardieu"
      given-names: "François"
      orcid: "https://orcid.org/0000-0002-7287-0094"
    - family-names: "Fournier"
      given-names: "Christian"
      orcid: "https://orcid.org/0000-0001-7098-8278"
    - family-names: "Pradal"
      given-names: "Christophe"
      orcid: "https://orcid.org/0000-0002-2555-761X"

    title: "Phenomenal: An automatic open source library for 3D shoot architecture reconstruction and analysis for image-based plant phenotyping"
    doi: "10.1101/805739"
    journal: "bioRxiv"
    publisher: "Cold Spring Harbor Laboratory"
    abstract: "In the era of high-throughput visual plant phenotyping, it is crucial to design fully automated and flexible workflows able to derive quantitative traits from plant images. Over the last years, several software supports the extraction of architectural features of shoot systems. Yet currently no end-to-end systems are able to extract both 3D shoot topology and geometry of plants automatically from images on large datasets and a large range of species. In particular, these software essentially deal with dicotyledons, whose architecture is comparatively easier to analyze than monocotyledons. To tackle these challenges, we designed the Phenomenal software featured with: (i) a completely automatic workflow system including data import, reconstruction of 3D plant architecture for a range of species and quantitative measurements on the reconstructed plants; (ii) an open source library for the development and comparison of new algorithms to perform 3D shoot reconstruction and (iii) an integration framework to couple workflow outputs with existing models towards model-assisted phenotyping. Phenomenal analyzes a large variety of data sets and species from images of high-throughput phenotyping platform experiments to published data obtained in different conditions and provided in a different format. Phenomenal has been validated both on manual measurements and synthetic data simulated by 3D models. It has been also tested on other published datasets to reproduce a published semi-automatic reconstruction workflow in an automatic way. Phenomenal is available as an open-source software on a public repository."
    eprint: "https://www.biorxiv.org/content/early/2019/10/21/805739.full.pdf"
    url: "https://www.biorxiv.org/content/early/2019/10/21/805739"
    elocation-id: "805739"
    year: 2019
```
